CREATE DATABASE IF NOT EXISTS albuns;

USE albuns;

CREATE TABLE artistas (
	ARTISTA_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(90)
) ENGINE=InnoDB;

CREATE TABLE estilo (
	ESTILO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(90)
) ENGINE=InnoDB;

CREATE TABLE albuns (
	ALBUM_ID INT PRIMARY KEY AUTO_INCREMENT,
    ARTISTA_ID INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    PRECO DOUBLE NOT NULL,
    ESTILO_ID INT NOT NULL,
    
    FOREIGN KEY (ARTISTA_ID) REFERENCES artistas(ARTISTA_ID),
    FOREIGN KEY (ESTILO_ID) REFERENCES estilo(ESTILO_ID)
)ENGINE=InnoDB;
